### ISSUE TITLE
use of undeclared type `Color`

### ISSUE THREAD

**Issue by ffleader1** [bobahop/rust_filecrawler_fltk#2]
I tried to compile with fltk-rust version 1
However, I get that error.
`title.set_text_color(Color::Red);    use of undeclared type "Color"`
Please have a look at it. Thank you.

**Comment by bobahop** [comment]
Evidently there was a breaking change between fltk version 0.15.15 and  version 1. When  I have time I'll recompile with the latest fltk version.

**Comment by bobahop** [comment]
Now uses Align, Color and FrameType from enums. Code compiles with fltk version 1.0.14.
